version: '3.8'

services:
  app:
    build: .
    container_name: password-manager-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/password_manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres_prod
      - JWT_SECRET=your_production_secret_key
    depends_on:
      - db
    networks:
      - password-manager-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: password-manager-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=password_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - password-manager-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  password-manager-network:
    driver: bridge